### ISSUE TITLE
[question] not working thorin package

### ISSUE THREAD

**Issue by marksteven070289** [ensdomains/thorin#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.6.20

### Current Behavior

```
{
  "name": "XXXXX",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "NODE_NO_WARNINGS=1 next dev",
    "dev:glocal": "NEXT_PUBLIC_GRAPH_URI=http://localhost:8000/subgraphs/name/graphprotocol/ens pnpm dev:nlocal",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "reinstall": "sudo rm -rf node_modules && rm -rf pnpm-lock.yaml && pnpm install",
    "prepare": "husky install",
    "tenv": "ens-test-env -a",
    "denv": "pnpm tenv start -ns -nb --extra-time 11368000"
  },
  "dependencies": {
    "@ensdomains/thorin": "^0.6.20",
    "@rainbow-me/rainbowkit": "^0.7.3",
    "ethers": "^5.7.2",
    "i18next": "^22.0.2",
    "i18next-browser-languagedetector": "^6.1.8",
    "i18next-http-backend": "^1.4.4",
    "next": "^12.3.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-i18next": "^12.0.0",
    "react-transition-state": "^1.1.5",
    "styled-components": "^5.3.6",
    "wagmi": "0.6.8"
  },
  "devDependencies": {
    "@ensdomains/ens-test-env": "^0.3.2",
    "@types/node": "^18.11.3",
    "@types/react": "17.0.30",
    "@types/styled-components": "^5.1.26",
    "eslint": "7.32.0",
    "eslint-config-next": "^12.3.1",
    "husky": "^8.0.1",
    "typescript": "^4.8.4"
  }
}

```

_app.tsx:
```
import './../styles/globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import type { AppProps } from 'next/app';
import { useState } from 'react';
import { RainbowKitProvider, getDefaultWallets } from '@rainbow-me/rainbowkit';
import { chain, configureChains, createClient, WagmiConfig } from 'wagmi';
import { alchemyProvider } from 'wagmi/providers/alchemy';
import { publicProvider } from 'wagmi/providers/public';
import { I18nextProvider } from 'react-i18next';
import { ThemeProvider } from 'styled-components';
import { DefaultTheme, ThorinGlobalStyles } from '@ensdomains/thorin';


import i18n from '../i18n';
import MainContainer from './../layouts/MainContainer';

const { chains, provider, webSocketProvider } = configureChains(
  [
    // chain.mainnet,
    // chain.polygon,
    // chain.optimism,
    // chain.arbitrum,
    ...(process.env.NEXT_PUBLIC_ENABLE_TESTNETS === 'true'
      ? [chain.goerli, chain.kovan, chain.rinkeby, chain.ropsten]
      : []),
  ],
  [
    alchemyProvider({
      // This is Alchemy's default API key.
      // You can get your own at https://dashboard.alchemyapi.io
      apiKey: 'XXXXXXXXXXX',
    }),
    publicProvider(),
  ]
);

const { connectors } = getDefaultWallets({
  appName: 'RainbowKit App',
  chains,
});

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
  webSocketProvider,
});

function MyApp({ Component, pageProps }: AppProps) {
  const [theme, setTheme] = useState<DefaultTheme>({ mode: 'light' })

  return (
    <I18nextProvider i18n={i18n}>
      <WagmiConfig client={wagmiClient}>
        <RainbowKitProvider chains={chains}>
          <ThemeProvider theme={theme}>
            <ThorinGlobalStyles/>
            <MainContainer/>
          </ThemeProvider>
        </RainbowKitProvider>
      </WagmiConfig>
    </I18nextProvider>
  );
}

export default MyApp;
```

MainContainer.tsx:
```
import React from "react";
import { 
    Button
} from '@ensdomains/thorin';



function MainContainer() {
    return(
        <div>
            <Button>My button</Button>
        </div>
    )
}

export default MainContainer;

```

and run terminal:
`npm run dev`

```
> XXXX@0.1.0 dev
> NODE_NO_WARNINGS=1 next dev

warn  - Port 3000 is in use, trying 3001 instead.
ready - started server on 0.0.0.0:3001, url: http://localhost:3001
info  - Loaded env from /home/computer/Developer/XXXXX/YYY/.env
event - compiled client and server successfully in 5.1s (1038 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 220 ms (1046 modules)
error - TypeError: Cannot read properties of undefined (reading '4')
    at /home/computer/Developer/XXX/YYYY/node_modules/.pnpm/@ensdomains+thorin@0.6.20_6haozuff5ofofiwuoke6ixqiri/node_modules/@ensdomains/thorin/dist/index.cjs.js:182:19
    at me (/home/computer/Developer/XXXX/YYYY/node_modules/.pnpm/styled-components@5.3.6_sfoxds7t5ydpegc3knd667wn6m/node_modules/styled-components/dist/styled-components.cjs.js:1:14803)
    at e.generateAndInjectStyles (/home/computer/Developer/XXXX/YYYY/node_modules/.pnpm/styled-components@5.3.6_sfoxds7t5ydpegc3knd667wn6m/node_modules/styled-components/dist/styled-components.cjs.js:1:11824)
    at /home/computer/Developer/XXXX/YYYY/node_modules/.pnpm/styled-components@5.3.6_sfoxds7t5ydpegc3knd667wn6m/node_modules/styled-components/dist/styled-components.cjs.js:1:18599
    at /home/computer/Developer/XXXX/YYYY/node_modules/.pnpm/styled-components@5.3.6_sfoxds7t5ydpegc3knd667wn6m/node_modules/styled-components/dist/styled-components.cjs.js:1:18743
    at Object.I [as render] (/home/computer/Developer/XXXX/YYYY/node_modules/.pnpm/styled-components@5.3.6_sfoxds7t5ydpegc3knd667wn6m/node_modules/styled-components/dist/styled-components.cjs.js:1:19189)
    at ReactDOMServerRenderer.render (/home/computer/Developer/XXX/YYY/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3872:44)
    at ReactDOMServerRenderer.read (/home/computer/Developer/XXXX/YYYY/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/home/computer/Developer/XXXX/YYYY/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/computer/Developer/XXX/YYY/node_modules/.pnpm/next@12.3.1_sfoxds7t5ydpegc3knd667wn6m/node_modules/next/dist/server/render.js:680:46) {
  page: '/'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 196 ms (1047 modules)

```

I don't understand what wrong...

**Comment by danielbelfort** [comment]
Having the same issue - in my case: TypeError: Cannot read properties of undefined (reading '2')

**Comment by foreseaz** [comment]
Seems that there're issues with the example theme setup, you can try 

```
    <ThemeProvider theme={lightTheme}> // explicitly define the lightTheme here
      <ThorinGlobalStyles />
      {children}
   </ThemeProvider>
```
